const stories = [
  {
    id: 0,
    date: new Date(2022, 4, 1),
    comment: 'I saw so many cats today. They were so cute!',
    emotion: 'Panic',
    imgLink: require('../../assets/stories/0.jpg'),
  },
  {
    id: 1,
    date: new Date(2022, 4, 2),
    comment: 'Tiramisu and americano with my friends.',
    emotion: 'Joyful',
    imgLink: require('../../assets/stories/1.jpg'),
  },
  {
    id: 2,
    date: new Date(2022, 4, 3),
    comment: 'Why is the sun setting so early?',
    emotion: 'Angry',
    imgLink: require('../../assets/stories/2.jpg'),
  },
  {
    id: 3,
    date: new Date(2022, 4, 4),
    comment: 'My fav strawberry chocolate cake.',
    emotion: 'Happy',
    imgLink: require('../../assets/stories/3.jpg'),
  },
  {
    id: 4,
    date: new Date(2022, 4, 5),
    comment: 'The weather was perfect.',
    emotion: 'Love',
    imgLink: require('../../assets/stories/4.jpg'),
  },
  {
    id: 5,
    date: new Date(2022, 4, 6),
    comment: "Going home. I'm so tired.",
    emotion: 'Sick',
    imgLink: require('../../assets/stories/5.jpg'),
  },
  {
    id: 6,
    date: new Date(2022, 4, 7),
    comment: 'Sunset with clouds.',
    emotion: 'Amazed',
    imgLink: require('../../assets/stories/6.jpg'),
  },
  {
    id: 7,
    date: new Date(2022, 4, 8),
    comment: 'It is so hot today. Am I in a sauna?',
    emotion: 'Panic',
    imgLink: require('../../assets/stories/7.jpg'),
  },
  {
    id: 8,
    date: new Date(2022, 4, 9),
    comment: "This is what my friend's done.",
    emotion: 'Angry',
    imgLink: require('../../assets/stories/8.jpg'),
  },
  {
    id: 9,
    date: new Date(2022, 4, 10),
    comment: 'Saw a fountain show. It was so beautiful.',
    emotion: 'Amazed',
    imgLink: require('../../assets/stories/9.jpg'),
  },
  {
    id: 10,
    date: new Date(2022, 4, 23),
    comment: 'My heart fluttered seeing these beautiful flowers',
    emotion: 'Shy',
    imgLink: require('../../assets/stories/10.jpg'),
  },
  {
    id: 11,
    date: new Date(2022, 4, 24),
    comment: 'Waiting for a bus. The sky was so beautiful.',
    emotion: 'Love',
    imgLink: require('../../assets/stories/11.jpg'),
  },
  {
    id: 12,
    date: new Date(2022, 4, 25),
    comment: 'Petals under my feet.',
    emotion: 'Shy',
    imgLink: require('../../assets/stories/12.jpg'),
  },
  {
    id: 13,
    date: new Date(2022, 4, 26),
    comment: "Spring has come. It's cherry blossom everywhere.",
    emotion: 'Shy',
    imgLink: require('../../assets/stories/13.jpg'),
  },
  {
    id: 14,
    date: new Date(2022, 4, 27),
    comment: 'Oreo Bingsu with my friends.',
    emotion: 'Happy',
    imgLink: require('../../assets/stories/14.jpg'),
  },
  {
    id: 15,
    date: new Date(2022, 4, 28),
    comment: 'Cute street lights. Makes me feel good.',
    emotion: 'Love',
    imgLink: require('../../assets/stories/15.jpg'),
  },
  {
    id: 16,
    date: new Date(2022, 4, 29),
    comment: 'Walking down along the Han river.',
    emotion: 'Amazed',
    imgLink: require('../../assets/stories/16.jpg'),
  },
  {
    id: 17,
    date: new Date(2022, 4, 30),
    comment: 'I caught the corona virus. My throat hurts.',
    emotion: 'Sick',
    imgLink: require('../../assets/stories/17.jpg'),
  },
  {
    id: 18,
    date: new Date(2022, 4, 31),
    comment: 'Drinking makgeolli with my girls',
    emotion: 'Laugh',
    imgLink: require('../../assets/stories/18.jpg'),
  },
  {
    id: 19,
    date: new Date(2022, 5, 1),
    comment: 'Having fun with my friends at Hapjeong.',
    emotion: 'Laugh',
    imgLink: require('../../assets/stories/19.jpg'),
  },
  {
    id: 20,
    date: new Date(2022, 5, 2),
    comment: 'sweet mango!',
    emotion: 'Joyful',
    imgLink: require('../../assets/stories/20.jpg'),
  },
  {
    id: 21,
    date: new Date(2022, 5, 3),
    comment: 'Omg the cat is so adorable!',
    emotion: 'Panic',
    imgLink: require('../../assets/stories/21.jpg'),
  },
  {
    id: 22,
    date: new Date(2022, 5, 4),
    comment: "I'm at Lotte World right now!",
    emotion: 'Happy',
    imgLink: require('../../assets/stories/22.jpg'),
  },
  {
    id: 23,
    date: new Date(2022, 5, 5),
    comment: '',
    emotion: 'Happy',
    imgLink: require('../../assets/stories/23.jpg'),
  },
  {
    id: 24,
    date: new Date(2022, 5, 6),
    comment: 'That crow took my snack away...',
    emotion: 'Angry',
    imgLink: require('../../assets/stories/24.jpg'),
  },
];

export default stories;
