const stories = [
  {
    id: 1,
    date: new Date(2022, 4, 1).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/1.jpg'),
  },
  {
    id: 2,
    date: new Date(2022, 4, 2).toDateString(),
    comment: 'good',
    emotion: 'Amazed',
    imgLink: require('../../assets/stories/2.jpg'),
  },
  {
    id: 3,
    date: new Date(2022, 4, 3).toDateString(),
    comment: 'good',
    emotion: 'Angry',
    imgLink: require('../../assets/stories/3.jpg'),
  },
  {
    id: 4,
    date: new Date(2022, 4, 4).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/4.jpg'),
  },
  {
    id: 5,
    date: new Date(2022, 4, 5).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/5.jpg'),
  },
  {
    id: 6,
    date: new Date(2022, 4, 6).toDateString(),
    comment: 'good',
    emotion: 'Joyful',
    imgLink: require('../../assets/stories/6.jpg'),
  },
  {
    id: 7,
    date: new Date(2022, 4, 7).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/7.jpg'),
  },
  {
    id: 8,
    date: new Date(2022, 4, 8).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/8.jpg'),
  },
  {
    id: 9,
    date: new Date(2022, 4, 9).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/9.jpg'),
  },
  {
    id: 10,
    date: new Date(2022, 4, 23).toDateString(),
    comment: 'good',
    emotion: 'Shy',
    imgLink: require('../../assets/stories/10.jpg'),
  },
  {
    id: 11,
    date: new Date(2022, 4, 24).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/11.jpg'),
  },
  {
    id: 12,
    date: new Date(2022, 4, 25).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/12.jpg'),
  },
  {
    id: 13,
    date: new Date(2022, 4, 26).toDateString(),
    comment: 'good',
    emotion: 'Laugh',
    imgLink: require('../../assets/stories/13.jpg'),
  },
  {
    id: 14,
    date: new Date(2022, 4, 27).toDateString(),
    comment: 'good',
    emotion: 'Happy',
    imgLink: require('../../assets/stories/14.jpg'),
  },
  {
    id: 15,
    date: new Date(2022, 4, 28).toDateString(),
    comment: 'good',
    emotion: 'Sick',
    imgLink: require('../../assets/stories/15.jpg'),
  },
  {
    id: 16,
    date: new Date(2022, 4, 29).toDateString(),
    comment: 'good',
    emotion: 'Panic',
    imgLink: require('../../assets/stories/16.jpg'),
  },
  {
    id: 17,
    date: new Date(2022, 4, 30).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/17.jpg'),
  },
  {
    id: 18,
    date: new Date(2022, 4, 31).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/18.jpg'),
  },
  {
    id: 19,
    date: new Date(2022, 5, 1).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/19.jpg'),
  },
  {
    id: 20,
    date: new Date(2022, 5, 2).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/20.jpg'),
  },
  {
    id: 21,
    date: new Date(2022, 5, 3).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/21.jpg'),
  },
  {
    id: 22,
    date: new Date(2022, 5, 4).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/22.jpg'),
  },
  {
    id: 23,
    date: new Date(2022, 5, 5).toDateString(),
    comment: 'good',
    emotion: 'Happy',
    imgLink: require('../../assets/stories/23.jpg'),
  },
  {
    id: 24,
    date: new Date(2022, 5, 6).toDateString(),
    comment: 'good',
    emotion: 'Love',
    imgLink: require('../../assets/stories/24.jpg'),
  },
];

export default stories;
